name: CI

on:
  push:
    branches:
            - origin

jobs: 
    building:
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout code'
          uses: actions/checkout@v4
          
        - name: "Build Docker image"
          run: |
            docker build -t oluwaseun7/testing-docker: 1.0.1 .