name: CI

on:
  push:
    branches:
            - origin

jobs: 
    building:
        runs-on: ubuntu-latest

        steps:
        - name: "Checkout code"
          uses: actions/checkout@v4
          
        - name: "Build Docker image"
          run: |
            docker build -t oluwaseun7/testing-docker:1.1.1 .

        - name: "Login to Docker Hub"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
        - name: Push Docker image
          run: |
            docker push oluwaseun7/testing-docker:1.1.1
            
 
        - name: "Go to the repo for Helm"
          run: |
            
            git config --global user.email "adewumibode7@gmail.com"
            git config --global user.name "Oluwaseun186"
            git clone https://github.com/Oluwaseun186/testcluster.git testcluster
            cd testcluster/templates
            #string editor 
            sed -i 's/testing-docker:1.0.1/testing-docker:1.1.1/' deployment.yaml
            cat deployment.yaml
            git add -A
            git commit -m "Updated helm 1"
            git remote set-url origin https://x-access-token:${{ secrets.CI_CD }}@github.com/Oluwaseun186/testing.git
            git push testing origin
                       