name: CI

on:
  push:
    branches:
            - origin

jobs: 
    building:
        runs-on: ubuntu-latest

        steps:
        - name: "Checkout code"
          uses: actions/checkout@v4
          
        - name: "Build Docker image"
          run: |
            docker build -t oluwaseun7/testing-docker:1.0.1 .

        - name: "Login to Docker Hub"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
        - name: Push Docker image
          run: |
            docker push oluwaseun7/testing-docker:1.0.1
            
 
        - name: "Go to the repo for Helm"
          run: |

            git config --global user.email "adewumibode7@gmail.com"
            git config --global user.name "Oluwaseun186"
            git clone https://github.com/Oluwaseun186/testcluster.git my-chart
            cd my-chart
            cd my-chart/templates

            #string editor 
            sed -i 's/testing:1/testing:2/' deployment.yaml
            cat deployment.yaml
            git add -A
            git commit -m "Updated helm"
                       